source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3', '>= 6.1.3.2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'
gem 'graphiti'
gem 'graphiti-rails'
gem 'kaminari', '~> 1.1'
gem 'responders', '~> 3.0'
gem 'rubocop'
gem 'twilio-ruby', '~> 5.54.1'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'vandal_ui'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'dotenv-rails'
  gem 'spring'
end

group :development, :test do
  gem 'factory_bot_rails', '~> 5.0'
  gem 'faker', '~> 2.5'
  gem 'graphiti_spec_helpers'
  gem 'pry', '~> 0.13.1'
  gem 'rspec-rails', '~> 4.0.0beta2'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner', '~> 1.7'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end
